id: IC27C544C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:10:35+00:00'
last_modified: '2022-06-08T11:03:32.114866+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9015
  title: འཁྲུལ་འཇོམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    1A4B:
      image_group_id: I1KG9046
      title: ''
      total_pages: 448
      order: 1
      base_file: 1A4B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
